 - name: Deploy maven Artifact
   hosts: localhost
   become: no
   tasks:
     - name: Create Directory
       ansible.builtin.file:
         path: /opt/deployment
         state: directory
         mode: '0755'
